
import type { Radical, CharacterComposition, Challenge } from './types';

export const RADICALS: Radical[] = [
  { id: 'ren_standing', symbol: '亻', name: 'standing person' },
  { id: 'men', symbol: '门', name: 'gate' },
  { id: 'mu', symbol: '木', name: 'tree' },
  { id: 'nu', symbol: '女', name: 'woman' },
  { id: 'zi', symbol: '子', name: 'child' },
  { id: 'kou', symbol: '口', name: 'mouth' },
  { id: 'ri', symbol: '日', name: 'sun' },
  { id: 'yue', symbol: '月', name: 'moon' },
  { id: 'er', symbol: '尔', name: 'you (literary)' },
  { id: 'xin', symbol: '心', name: 'heart' },
  { id: 'shui', symbol: '氵', name: 'water' },
  { id: 'huo_radical', symbol: '灬', name: 'fire radical' },
  { id: 'tu', symbol: '土', name: 'earth' },
  { id: 'jin_gold', symbol: '金', name: 'gold' },
  { id: 'shan', symbol: '山', name: 'mountain' },
  { id: 'ren', symbol: '人', name: 'person' },
  { id: 'he', symbol: '禾', name: 'grain' },
  { id: 'tian', symbol: '田', name: 'field' },
  { id: 'li', symbol: '力', name: 'power' },
  { id: 'yan_speech', symbol: '讠', name: 'speech' },
  { id: 'she', symbol: '舌', name: 'tongue' },
  { id: 'shou_hand', symbol: '扌', name: 'hand' },
  { id: 'yu_jade', symbol: '王', name: 'jade (king)' }, // Often used for jade radical
  { id: 'ma_horse', symbol: '马', name: 'horse' },
  { id: 'shi_stone', symbol: '石', name: 'stone' },
  { id: 'gong_work', symbol: '工', name: 'work' },
  { id: 'ding', symbol: '丁', name: 'nail/cube' },
  { id: 'yuan', symbol: '元', name: 'first/primary' },
  { id: 'pi', symbol: '皮', name: 'skin' },
  { id: 'yi_one', symbol: '一', name: 'one' },
  { id: 'gun_line', symbol: '丨', name: 'line' },
  { id: 'zhu_dot', symbol: '丶', name: 'dot' },
  { id: 'pie_slash', symbol: '丿', name: 'slash' },
  { id: 'da_big', symbol: '大', name: 'big' },
  { id: 'ru_enter', symbol: '入', name: 'enter' },
  { id: 'ba_eight', symbol: '八', name: 'eight' },
  { id: 'bing_ice', symbol: '冫', name: 'ice' },
  { id: 'xiao_small', symbol: '小', name: 'small' },
  { id: 'shi_corpse', symbol: '尸', name: 'corpse' },
  { id: 'cun_inch', symbol: '寸', name: 'inch' },
  { id: 'jin_towel', symbol: '巾', name: 'towel' },
  { id: 'you_again', symbol: '又', name: 'again' },
  { id: 'bai_white', symbol: '白', name: 'white' },
  { id: 'mu_eye', symbol: '目', name: 'eye' },
  { id: 'dao_knife', symbol: '刀', name: 'knife' },
  { id: 'gong_bow', symbol: '弓', name: 'bow' },
  { id: 'shen_body', symbol: '身', name: 'body' },
  { id: 'chang_cliff', symbol: '厂', name: 'cliff' },
  { id: 'bi_spoon', symbol: '匕', name: 'spoon' },
  { id: 'jin_now', symbol: '今', name: 'now' },
  { id: 'quan_dog', symbol: '犬', name: 'dog' },
  { id: 'wei_enclosure', symbol: '囗', name: 'enclosure' },
  { id: 'bao_gai', symbol: '宀', name: 'roof' },
  { id: 'jiong', symbol: '冂', name: 'down box' },
  { id: 'mi_cover', symbol: '冖', name: 'cover' },
  { id: 'ji_table', symbol: '几', name: 'table' },
  { id: 'zhi_stop', symbol: '止', name: 'stop' },
  { id: 'chi_step', symbol: '彳', name: 'double person' },
  { id: 'zou_walk', symbol: '走', name: 'walk' },
  { id: 'shi_ten', symbol: '十', name: 'ten' },
  { id: 'wei_notyet', symbol: '未', name: 'not yet' },
  { id: 'qie_and', symbol: '且', name: 'and/also' },
];

export const CHARACTERS: CharacterComposition[] = [
  {
    character: '你',
    // Structure: [亻, 尔, null, null] (left-right, top row)
    components: ['亻', '尔', null, null],
    pinyin: 'nǐ',
    meaning: 'you',
    usage: '你好 (nǐ hǎo) - Hello',
  },
  {
    character: '你',
    // Structure: [null, null, 亻, 尔] (left-right, bottom row)
    components: [null, null, '亻', '尔'],
    pinyin: 'nǐ',
    meaning: 'you',
    usage: '你好 (nǐ hǎo) - Hello',
  },
  {
    character: '好',
    // Structure: [女, 子, null, null] (left-right, top row)
    components: ['女', '子', null, null],
    pinyin: 'hǎo',
    meaning: 'good, well',
    usage: '你好 (nǐ hǎo) - Hello',
  },
  {
    character: '好',
    // Structure: [null, null, 女, 子] (left-right, bottom row)
    components: [null, null, '女', '子'],
    pinyin: 'hǎo',
    meaning: 'good, well',
    usage: '你好 (nǐ hǎo) - Hello',
  },
  {
    character: '们',
    // Structure: [亻, 门, null, null] (left-right, top row)
    components: ['亻', '门', null, null],
    pinyin: 'men',
    meaning: 'plural suffix for pronouns',
    usage: '我们 (wǒmen) - we, us',
  },
    {
    character: '们',
    // Structure: [null, null, 亻, 门] (left-right, bottom row)
    components: [null, null, '亻', '门'],
    pinyin: 'men',
    meaning: 'plural suffix for pronouns',
    usage: '我们 (wǒmen) - we, us',
  },
  {
    character: '林',
    // Structure: [木, 木, null, null] (left-right, top row)
    components: ['木', '木', null, null],
    pinyin: 'lín',
    meaning: 'forest, woods',
    usage: '森林 (sēnlín) - forest',
  },
  {
    character: '林',
    // Structure: [null, null, 木, 木] (left-right, bottom row)
    components: [null, null, '木', '木'],
    pinyin: 'lín',
    meaning: 'forest, woods',
    usage: '森林 (sēnlín) - forest',
  },
  {
    character: '森',
    components: ['木', '木', '木', null],
    pinyin: 'sēn',
    meaning: 'forest',
    usage: '森林 (sēnlín) - forest',
  },
  {
    character: '明',
    // Structure: [日, 月, null, null] (left-right, top row)
    components: ['日', '月', null, null],
    pinyin: 'míng',
    meaning: 'bright, clear',
    usage: '明天 (míngtiān) - tomorrow',
  },
    {
    character: '明',
    // Structure: [null, null, 日, 月] (left-right, bottom row)
    components: [null, null, '日', '月'],
    pinyin: 'míng',
    meaning: 'bright, clear',
    usage: '明天 (míngtiān) - tomorrow',
  },
  {
    character: '呆',
    // Structure: [口, 木, null, null] (left-right, top row)
    components: ['口', '木', null, null],
    pinyin: 'dāi',
    meaning: 'dull, foolish, to stay',
    usage: '发呆 (fādāi) - to stare blankly',
  },
    {
    character: '呆',
    // Structure: [null, null, 口, 木] (left-right, bottom row)
    components: [null, null, '口', '木'],
    pinyin: 'dāi',
    meaning: 'dull, foolish, to stay',
    usage: '发呆 (fādāi) - to stare blankly',
  },
  {
    character: '休',
    // Structure: [亻, 木, null, null] (left-right, top row)
    components: ['亻', '木', null, null],
    pinyin: 'xiū',
    meaning: 'rest',
    usage: '休息 (xiūxi) - to take a rest',
  },
    {
    character: '休',
    // Structure: [null, null, 亻, 木] (left-right, bottom row)
    components: [null, null, '亻', '木'],
    pinyin: 'xiū',
    meaning: 'rest',
    usage: '休息 (xiūxi) - to take a rest',
  },
  {
    character: '从',
    // Structure: [人, 人, null, null] (left-right, top row)
    components: ['人', '人', null, null],
    pinyin: 'cóng',
    meaning: 'from, follow',
    usage: '从来 (cónglái) - always, from the beginning',
  },
    {
    character: '从',
    // Structure: [null, null, 人, 人] (left-right, bottom row)
    components: [null, null, '人', '人'],
    pinyin: 'cóng',
    meaning: 'from, follow',
    usage: '从来 (cónglái) - always, from the beginning',
  },
  {
    character: '仙',
    // Structure: [亻, 山, null, null] (left-right, top row)
    components: ['亻', '山', null, null],
    pinyin: 'xiān',
    meaning: 'immortal, transcendent',
    usage: '神仙 (shénxiān) - deity, immortal',
  },
    {
    character: '仙',
    // Structure: [null, null, 亻, 山] (left-right, bottom row)
    components: [null, null, '亻', '山'],
    pinyin: 'xiān',
    meaning: 'immortal, transcendent',
    usage: '神仙 (shénxiān) - deity, immortal',
  },
  {
    character: '问',
    // Structure: enclosure 门 over 口 (top-left, bottom-left)
    components: ['门', null, '口', null],
    pinyin: 'wèn',
    meaning: 'ask',
    usage: '问题 (wèntí) - question, problem',
  },
  {
    character: '问',
    // Structure: enclosure 门 over 口 (top-right, bottom-right)
    components: [null, '门', null, '口'],
    pinyin: 'wèn',
    meaning: 'ask',
    usage: '问题 (wèntí) - question, problem',
  },
  {
    character: '间',
    // Structure: enclosure 门 over 日 (top-left, bottom-left)
    components: ['门', null, '日', null],
    pinyin: 'jiān',
    meaning: 'space, between',
    usage: '时间 (shíjiān) - time',
  },
  {
    character: '间',
    // Structure: enclosure 门 over 日 (top-right, bottom-right)
    components: [null, '门', null, '日'],
    pinyin: 'jiān',
    meaning: 'space, between',
    usage: '时间 (shíjiān) - time',
  },
  {
    character: '男',
    // Structure: 田 over 力 (top-left, bottom-left)
    components: ['田', null, '力', null],
    pinyin: 'nán',
    meaning: 'male, man',
    usage: '男人 (nánrén) - man',
  },
  {
    character: '男',
    // Structure: 田 over 力 (top-right, bottom-right)
    components: [null, '田', null, '力'],
    pinyin: 'nán',
    meaning: 'male, man',
    usage: '男人 (nánrén) - man',
  },
  {
    character: '香',
    // Structure: 禾 over 日 (top-left, bottom-left)
    components: ['禾', null, '日', null],
    pinyin: 'xiāng',
    meaning: 'fragrant, sweet-smelling',
    usage: '香水 (xiāngshuǐ) - perfume',
  },
    {
    character: '香',
    // Structure: 禾 over 日 (top-right, bottom-right)
    components: [null, '禾', null, '日'],
    pinyin: 'xiāng',
    meaning: 'fragrant, sweet-smelling',
    usage: '香水 (xiāngshuǐ) - perfume',
  },
  {
    character: '话',
    // Structure: [讠, 舌, null, null] (left-right, top row)
    components: ['讠', '舌', null, null],
    pinyin: 'huà',
    meaning: 'speech, language',
    usage: '说话 (shuōhuà) - to speak',
  },
    {
    character: '话',
    // Structure: [null, null, 讠, 舌] (left-right, bottom row)
    components: [null, null, '讠', '舌'],
    pinyin: 'huà',
    meaning: 'speech, language',
    usage: '说话 (shuōhuà) - to speak',
  },
  {
    character: '打',
    // Structure: [扌, 丁, null, null] (left-right, top row)
    components: ['扌', '丁', null, null],
    pinyin: 'dǎ',
    meaning: 'to hit, to strike',
    usage: '打球 (dǎ qiú) - to play ball',
  },
  {
    character: '打',
    // Structure: [null, null, 扌, 丁] (left-right, bottom row)
    components: [null, null, '扌', '丁'],
    pinyin: 'dǎ',
    meaning: 'to hit, to strike',
    usage: '打球 (dǎ qiú) - to play ball',
  },
  {
    character: '玩',
    // Structure: [王, 元, null, null] (left-right, top row)
    components: ['王', '元', null, null],
    pinyin: 'wán',
    meaning: 'to play',
    usage: '玩具 (wánjù) - toy',
  },
  {
    character: '玩',
    // Structure: [null, null, 王, 元] (left-right, bottom row)
    components: [null, null, '王', '元'],
    pinyin: 'wán',
    meaning: 'to play',
    usage: '玩具 (wánjù) - toy',
  },
  {
    character: '妈',
    // Structure: [女, 马, null, null] (left-right, top row)
    components: ['女', '马', null, null],
    pinyin: 'mā',
    meaning: 'mother',
    usage: '妈妈 (māma) - mom',
  },
  {
    character: '妈',
    // Structure: [null, null, 女, 马] (left-right, bottom row)
    components: [null, null, '女', '马'],
    pinyin: 'mā',
    meaning: 'mother',
    usage: '妈妈 (māma) - mom',
  },
  {
    character: '破',
    // Structure: [石, 皮, null, null] (left-right, top row)
    components: ['石', '皮', null, null],
    pinyin: 'pò',
    meaning: 'to break, broken',
    usage: '打破 (dǎpò) - to break',
  },
  {
    character: '破',
    // Structure: [null, null, 石, 皮] (left-right, bottom row)
    components: [null, null, '石', '皮'],
    pinyin: 'pò',
    meaning: 'to break, broken',
    usage: '打破 (dǎpò) - to break',
  },
  {
    character: '天',
    components: ['一', null, '大', null],
    pinyin: 'tiān',
    meaning: 'sky, heaven, day',
    usage: '今天 (jīntiān) - today',
  },
    {
    character: '天',
    components: [null, '一', null, '大'],
    pinyin: 'tiān',
    meaning: 'sky, heaven, day',
    usage: '今天 (jīntiān) - today',
  },
  {
    character: '尘',
    components: ['小', null, '土', null],
    pinyin: 'chén',
    meaning: 'dust',
    usage: '灰尘 (huīchén) - dust',
  },
  {
    character: '尘',
    components: [null, '小', null, '土'],
    pinyin: 'chén',
    meaning: 'dust',
    usage: '灰尘 (huīchén) - dust',
  },
  {
    character: '寺',
    components: ['土', null, '寸', null],
    pinyin: 'sì',
    meaning: 'temple',
    usage: '寺庙 (sìmiào) - temple',
  },
  {
    character: '寺',
    components: [null, '土', null, '寸'],
    pinyin: 'sì',
    meaning: 'temple',
    usage: '寺庙 (sìmiào) - temple',
  },
  {
    character: '层',
    components: ['尸', null, '云', null], // This is a simplification, '云' is not a radical here
    pinyin: 'céng',
    meaning: 'layer, story, floor',
    usage: '一层 (yī céng) - first floor',
  },
  {
    character: '相',
    components: ['木', '目', null, null],
    pinyin: 'xiāng',
    meaning: 'mutual, each other',
    usage: '互相 (hùxiāng) - each other',
  },
  {
    character: '相',
    components: [null, null, '木', '目'],
    pinyin: 'xiāng',
    meaning: 'mutual, each other',
    usage: '互相 (hùxiāng) - each other',
  },
  {
    character: '对',
    components: ['又', '寸', null, null],
    pinyin: 'duì',
    meaning: 'correct, pair',
    usage: '对不对 (duì bu duì) - Is that right?',
  },
  {
    character: '对',
    components: [null, null, '又', '寸'],
    pinyin: 'duì',
    meaning: 'correct, pair',
    usage: '对不对 (duì bu duì) - Is that right?',
  },
  {
    character: '旦',
    components: ['日', null, '一', null],
    pinyin: 'dàn',
    meaning: 'dawn',
    usage: '元旦 (yuándàn) - New Year\'s Day',
  },
  {
    character: '旦',
    components: [null, '日', null, '一'],
    pinyin: 'dàn',
    meaning: 'dawn',
    usage: '元旦 (yuándàn) - New Year\'s Day',
  },
  {
    character: '分',
    components: ['八', null, '刀', null],
    pinyin: 'fēn',
    meaning: 'divide, minute, point',
    usage: '分开 (fēnkāi) - to separate',
  },
  {
    character: '分',
    components: [null, '八', null, '刀'],
    pinyin: 'fēn',
    meaning: 'divide, minute, point',
    usage: '分开 (fēnkāi) - to separate',
  },
  {
    character: '引',
    components: ['弓', '丨', null, null],
    pinyin: 'yǐn',
    meaning: 'to pull, to draw',
    usage: '引起 (yǐnqǐ) - to cause',
  },
  {
    character: '引',
    components: [null, null, '弓', '丨'],
    pinyin: 'yǐn',
    meaning: 'to pull, to draw',
    usage: '引起 (yǐnqǐ) - to cause',
  },
  {
    character: '火',
    components: ['人', '丶', null, null],
    pinyin: 'huǒ',
    meaning: 'fire',
    usage: '火山 (huǒshān) - volcano',
  },
  {
    character: '火',
    components: [null, null, '人', '丶'],
    pinyin: 'huǒ',
    meaning: 'fire',
    usage: '火山 (huǒshān) - volcano',
  },
  {
    character: '人',
    components: ['丿', '丶', null, null],
    pinyin: 'rén',
    meaning: 'person, people',
    usage: '人民 (rénmín) - the people',
  },
  {
    character: '人',
    components: [null, null, '丿', '丶'],
    pinyin: 'rén',
    meaning: 'person, people',
    usage: '人民 (rénmín) - the people',
  },
  {
    character: '岑',
    components: ['山', null, '今', null],
    pinyin: 'cén',
    meaning: 'high mountain peak',
    usage: '岑寂 (cénjì) - deathly still',
  },
  {
    character: '岑',
    components: [null, '山', null, '今'],
    pinyin: 'cén',
    meaning: 'high mountain peak',
    usage: '岑寂 (cénjì) - deathly still',
  },
  {
    character: '吠',
    components: ['口', '犬', null, null],
    pinyin: 'fèi',
    meaning: 'to bark',
    usage: '狗吠 (gǒu fèi) - The dog barks.',
  },
  {
    character: '吠',
    components: [null, null, '口', '犬'],
    pinyin: 'fèi',
    meaning: 'to bark',
    usage: '狗吠 (gǒu fèi) - The dog barks.',
  },
  {
    character: '旧',
    components: ['日', null, '丨', null],
    pinyin: 'jiù',
    meaning: 'old, former',
    usage: '旧书 (jiù shū) - old book',
  },
  {
    character: '旧',
    components: [null, '日', null, '丨'],
    pinyin: 'jiù',
    meaning: 'old, former',
    usage: '旧书 (jiù shū) - old book',
  },
  {
    character: '吟',
    components: ['口', '今', null, null],
    pinyin: 'yín',
    meaning: 'to chant, to recite',
    usage: '吟诗 (yín shī) - to recite poetry',
  },
  {
    character: '吟',
    components: [null, null, '口', '今'],
    pinyin: 'yín',
    meaning: 'to chant, to recite',
    usage: '吟诗 (yín shī) - to recite poetry',
  },
  {
    character: '坐',
    components: ['人', '人', '土', null],
    pinyin: 'zuò',
    meaning: 'to sit',
    usage: '请坐 (qǐng zuò) - Please sit.',
  },
  {
    character: '谢',
    components: ['讠', '身', null, '寸'],
    pinyin: 'xiè',
    meaning: 'thank',
    usage: '谢谢 (xièxie) - Thank you',
  },
  {
    character: '什',
    components: ['亻', '十', null, null],
    pinyin: 'shén',
    meaning: 'what',
    usage: '什么 (shénme) - what?',
  },
  {
    character: '什',
    components: [null, null, '亻', '十'],
    pinyin: 'shén',
    meaning: 'what',
    usage: '什么 (shénme) - what?',
  },
  {
    character: '扛',
    components: ['扌', '工', null, null],
    pinyin: 'káng',
    meaning: 'to carry on the shoulder',
    usage: '把米袋扛起来 (bǎ mǐdài káng qǐlái) - Hoist the rice bag onto your shoulder.',
  },
  {
    character: '扛',
    components: [null, null, '扌', '工'],
    pinyin: 'káng',
    meaning: 'to carry on the shoulder',
    usage: '把米袋扛起来 (bǎ mǐdài káng qǐlái) - Hoist the rice bag onto your shoulder.',
  },
  {
    character: '吐',
    components: ['口', '土', null, null],
    pinyin: 'tǔ',
    meaning: 'to spit',
    usage: '吐痰 (tǔ tán) - to spit phlegm',
  },
  {
    character: '吐',
    components: [null, null, '口', '土'],
    pinyin: 'tǔ',
    meaning: 'to spit',
    usage: '吐痰 (tǔ tán) - to spit phlegm',
  },
  {
    character: '叭',
    components: ['口', '八', null, null],
    pinyin: 'bā',
    meaning: 'to babble, trumpet sound',
    usage: '喇叭 (lǎbā) - trumpet, horn',
  },
  {
    character: '叭',
    components: [null, null, '口', '八'],
    pinyin: 'bā',
    meaning: 'to babble, trumpet sound',
    usage: '喇叭 (lǎbā) - trumpet, horn',
  },
  {
    character: '叮',
    components: ['口', '丁', null, null],
    pinyin: 'dīng',
    meaning: 'to sting, to bite; to say again',
    usage: '叮嘱 (dīngzhǔ) - to urge, to exhort',
  },
  {
    character: '叮',
    components: [null, null, '口', '丁'],
    pinyin: 'dīng',
    meaning: 'to sting, to bite; to say again',
    usage: '叮嘱 (dīngzhǔ) - to urge, to exhort',
  },
  {
    character: '困',
    components: ['囗', '木', null, null],
    pinyin: 'kùn',
    meaning: 'sleepy, trapped',
    usage: '我好困 (wǒ hǎo kùn) - I am so sleepy.',
  },
  {
    character: '闪',
    components: ['门', '人', null, null],
    pinyin: 'shǎn',
    meaning: 'to flash, to dodge',
    usage: '闪电 (shǎndiàn) - lightning',
  },
  {
    character: '闪',
    components: [null, '门', null, '人'],
    pinyin: 'shǎn',
    meaning: 'to flash, to dodge',
    usage: '闪电 (shǎndiàn) - lightning',
  },
  {
    character: '国',
    components: ['囗', '王', '丶', null],
    pinyin: 'guó',
    meaning: 'country, nation, kingdom',
    usage: '中国 (Zhōngguó) - China',
  },
  {
    character: '安',
    components: ['宀', null, '女', null],
    pinyin: 'ān',
    meaning: 'peace, secure',
    usage: '安全 (ānquán) - safe, safety',
  },
  {
    character: '安',
    components: [null, '宀', null, '女'],
    pinyin: 'ān',
    meaning: 'peace, secure',
    usage: '安全 (ānquán) - safe, safety',
  },
  {
    character: '内',
    components: ['冂', '人', null, null],
    pinyin: 'nèi',
    meaning: 'inside, inner',
    usage: '内容 (nèiróng) - content',
  },
  {
    character: '冗',
    components: ['冖', null, '几', null],
    pinyin: 'rǒng',
    meaning: 'superfluous, unnecessary',
    usage: '冗长 (rǒngcháng) - tediously long',
  },
  {
    character: '此',
    components: ['止', '匕', null, null],
    pinyin: 'cǐ',
    meaning: 'this, here',
    usage: '此地 (cǐdì) - this place',
  },
  {
    character: '此',
    components: [null, null, '止', '匕'],
    pinyin: 'cǐ',
    meaning: 'this, here',
    usage: '此地 (cǐdì) - this place',
  },
  {
    character: '正',
    components: ['一', null, '止', null],
    pinyin: 'zhèng',
    meaning: 'correct, straight',
    usage: '正确 (zhèngquè) - correct, proper',
  },
  {
    character: '正',
    components: [null, '一', null, '止'],
    pinyin: 'zhèng',
    meaning: 'correct, straight',
    usage: '正确 (zhèngquè) - correct, proper',
  },
  {
    character: '步',
    components: ['止', '小', '丿', null],
    pinyin: 'bù',
    meaning: 'step, walk',
    usage: '走路 (zǒulù) - to walk',
  },
  {
    character: '址',
    components: ['土', '止', null, null],
    pinyin: 'zhǐ',
    meaning: 'location, site',
    usage: '地址 (dìzhǐ) - address',
  },
  {
    character: '址',
    components: [null, null, '土', '止'],
    pinyin: 'zhǐ',
    meaning: 'location, site',
    usage: '地址 (dìzhǐ) - address',
  },
  {
    character: '徙',
    components: ['彳', '走', null, null],
    pinyin: 'xǐ',
    meaning: 'to move, to migrate',
    usage: '迁徙 (qiānxǐ) - to migrate',
  },
  {
    character: '徙',
    components: [null, null, '彳', '走'],
    pinyin: 'xǐ',
    meaning: 'to move, to migrate',
    usage: '迁徙 (qiānxǐ) - to migrate',
  },
  {
    character: '征',
    components: ['彳', '正', null, null],
    pinyin: 'zhēng',
    meaning: 'to journey, to attack',
    usage: '长征 (Chángzhēng) - The Long March',
  },
  {
    character: '征',
    components: [null, null, '彳', '正'],
    pinyin: 'zhēng',
    meaning: 'to journey, to attack',
    usage: '长征 (Chángzhēng) - The Long March',
  },
  {
    character: '走',
    components: ['土', null, '止', null],
    pinyin: 'zǒu',
    meaning: 'to walk, to go',
    usage: '走路 (zǒulù) - to walk',
  },
  {
    character: '走',
    components: [null, '土', null, '止'],
    pinyin: 'zǒu',
    meaning: 'to walk, to go',
    usage: '走路 (zǒulù) - to walk',
  },
  {
    character: '上',
    components: ['丨', null, '一', null],
    pinyin: 'shàng',
    meaning: 'up, on, above',
    usage: '上学 (shàng xué) - to go to school',
  },
  {
    character: '上',
    components: [null, '丨', null, '一'],
    pinyin: 'shàng',
    meaning: 'up, on, above',
    usage: '上学 (shàng xué) - to go to school',
  },
  {
    character: '下',
    components: ['一', null, '丨', null],
    pinyin: 'xià',
    meaning: 'down, under, below',
    usage: '下雨 (xià yǔ) - to rain',
  },
  {
    character: '下',
    components: [null, '一', null, '丨'],
    pinyin: 'xià',
    meaning: 'down, under, below',
    usage: '下雨 (xià yǔ) - to rain',
  },
  {
    character: '早',
    components: ['日', null, '十', null],
    pinyin: 'zǎo',
    meaning: 'early',
    usage: '早上好 (zǎoshang hǎo) - Good morning',
  },
  {
    character: '早',
    components: [null, '日', null, '十'],
    pinyin: 'zǎo',
    meaning: 'early',
    usage: '早上好 (zǎoshang hǎo) - Good morning',
  },
  {
    character: '午',
    components: ['丿', '十', null, null],
    pinyin: 'wǔ',
    meaning: 'noon',
    usage: '中午 (zhōngwǔ) - noon',
  },
  {
    character: '午',
    components: [null, null, '丿', '十'],
    pinyin: 'wǔ',
    meaning: 'noon',
    usage: '中午 (zhōngwǔ) - noon',
  },
  {
    character: '妹',
    components: ['女', '未', null, null],
    pinyin: 'mèi',
    meaning: 'younger sister',
    usage: '妹妹 (mèimei) - younger sister',
  },
  {
    character: '妹',
    components: [null, null, '女', '未'],
    pinyin: 'mèi',
    meaning: 'younger sister',
    usage: '妹妹 (mèimei) - younger sister',
  },
  {
    character: '姐',
    components: ['女', '且', null, null],
    pinyin: 'jiě',
    meaning: 'older sister',
    usage: '姐姐 (jiějie) - older sister',
  },
  {
    character: '姐',
    components: [null, null, '女', '且'],
    pinyin: 'jiě',
    meaning: 'older sister',
    usage: '姐姐 (jiějie) - older sister',
  },
  {
    character: '没',
    components: ['氵', '又', '几', null],
    pinyin: 'méi',
    meaning: 'not have, no',
    usage: '没有 (méiyǒu) - to not have',
  },
];

export const CHALLENGES: Challenge[] = [
  {
    id: 'challenge-1',
    targetCharacter: '好',
    pinyin: 'hǎo',
    meaning: 'good, well',
    allowedRadicals: ['女', '子', '木', '口'],
  },
  {
    id: 'challenge-2',
    targetCharacter: '林',
    pinyin: 'lín',
    meaning: 'forest, woods',
    allowedRadicals: ['木', '木', '日', '月'],
  },
  {
    id: 'challenge-3',
    targetCharacter: '明',
    pinyin: 'míng',
    meaning: 'bright, clear',
    allowedRadicals: ['女', '子', '日', '月'],
  },
  {
    id: 'challenge-4',
    targetCharacter: '打',
    pinyin: 'dǎ',
    meaning: 'to hit',
    allowedRadicals: ['扌', '丁', '女', '马'],
  },
  {
    id: 'challenge-5',
    targetCharacter: '妈',
    pinyin: 'mā',
    meaning: 'mother',
    allowedRadicals: ['女', '马', '石', '皮'],
  },
  {
    id: 'challenge-6',
    targetCharacter: '破',
    pinyin: 'pò',
    meaning: 'to break',
    allowedRadicals: ['石', '皮', '土', '目'],
  },
  {
    id: 'challenge-7',
    targetCharacter: '天',
    pinyin: 'tiān',
    meaning: 'sky',
    allowedRadicals: ['一', '大', '人', '小'],
  },
];
